Solve bug about VIRTUAL_ENV variable in my-tmux-sessionizer

diff --git a/.local/bin/my-tmux-sessionizer b/.local/bin/my-tmux-sessionizer
--- a/.local/bin/my-tmux-sessionizer
+++ b/.local/bin/my-tmux-sessionizer
@@ -34,6 +34,7 @@ mode=""
 session_idx=""
 window_idx=""
 kill=""
+venv_window_idx=""
 
 while [[ "$#" -gt 0 ]]; do
     case "$1" in
@@ -45,7 +46,8 @@ while [[ "$#" -gt 0 ]]; do
         echo "                         Available modes are: 'fzf', 'session', 'window'."
         echo "  -s, --session <name>   Session command index."
         echo "  -w, --window <name>    Window command index." 
-        echo "  -k, --kill-window      Kills window where this program was called."
+        echo "  -k, --kill-window      Kill window where this program was called."
+        echo "  --venv-window          Load venv from specified window when mode = 'window'."
         exit 0
         ;;
 
@@ -82,6 +84,15 @@ while [[ "$#" -gt 0 ]]; do
 
     -k | --kill-window)
         kill=$(tmux display-message -p '#S:#I')
+        ;;
+
+    --venv-window)
+        venv_window_idx="$2"
+        shift # shifts arguments $2 -> $1, $3 -> $2, ...
+        if [[ -z "$venv_window_idx" || "$venv_window_idx" -lt 0 ]]; then
+            echo "Error: Invalid venv window index. Please provide an positive integer index."
+            exit 1
+        fi
         ;;
         
     *) # any other input
@@ -153,12 +164,18 @@ fzf_session() {
 
 open_window() {
     # create new window in current session if it does not exist and load the
-    # same virtual environment as the original window.
+    # same virtual environment as the specified window. See the comments in
+    # .tmux.conf for more information about this choice.
     if ! tmux list-windows -F '#I' | grep -q "^$window_idx$"; then
-        venv=$VIRTUAL_ENV
+        venv=""
+        if ! [[ -z $venv_window_idx ]]; then
+            venv=$(tmux show-window-options -t :$venv_window_idx -v @virtual_env)
+            echo "$venv_window_idx $venv" > log.txt
+        fi
         tmux new-window -t :$window_idx
         if ! [[ -z $venv ]]; then
             tmux send-keys -t :$window_idx "source ${venv}/bin/activate" C-m
+            tmux set-window-option -t :$window_idx @virtual_env "$venv"
             tmux send-keys -t :$window_idx "clear" C-m
         fi
     fi
