Load venv in fzf mode in my-tmux-sessionizer

diff --git a/.local/bin/my-tmux-sessionizer b/.local/bin/my-tmux-sessionizer
--- a/.local/bin/my-tmux-sessionizer
+++ b/.local/bin/my-tmux-sessionizer
@@ -161,6 +161,15 @@ fzf_session() {
     if ! tmux has-session -t $tmux_name 2>/dev/null; then
         # create this tmux session because it does not exist.
         tmux new-session -ds $tmux_name -c $dir
+        # load virtual environment only if the session does not exist.
+        # if the venv does not exist, the 'activate' command is going to fail
+        # but the output is going to be cleared by the 'clear' command.
+        venv="$name"
+        if ! [[ -z $venv ]]; then
+            # run the specific command on window 0 of the particular session. C-m = Enter key.
+            tmux send-keys -t $tmux_name:0 "activate $venv" C-m
+            tmux send-keys -t $tmux_name:0 "clear" C-m
+        fi
     fi
 
     if [[ -z $TMUX ]]; then
